import json

import sl.utils as utils


class BaseModel(object):

    """Base class for the whole api, based on code in the python-twitter library"""

    def __init__(self):
        self.default_params = {}

    def __str__(self):
        """Returns a jsonified string per default"""
        return self.to_json_string()

    def __eq__(self, other):
        return other and self.to_dictionary() == other.to_dictionary()

    def __ne__(self, other):
        return not self.__eq__(other)

    def _set_default_params(self, **data):
        """ The trafiklab api does respond in CamelCased we are using the util function to convert to snake_case"""
        for (param, default) in self.default_params.items():
            setattr(self, utils.to_snake_case(param), data.get(param, default))

    def to_json_string(self, sort_keys=True):
        """Returns a jsonified string based on the dictionary generated by to_dictionary"""
        return json.dumps(self.to_dictionary(), sort_keys=sort_keys)

    def to_dictionary(self):
        data = {}
        for (key, value) in self.default_params.items():
            snake_key = utils.to_snake_case(key)

            if isinstance(getattr(self, snake_key, None), (list, tuple, set)):
                data[snake_key] = list()
                for subobj in getattr(self, snake_key, None):
                    if getattr(subobj, 'to_dictionary', None):
                        data[snake_key].append(subobj.to_dictionary())
                    else:
                        data[snake_key].append(subobj)

            # Not a list, *but still a subclass of TrafiklabModel* and
            # and we can assign the data[snake_key] directly with the to_dictionary()
            # method of the object.
            elif getattr(getattr(self, snake_key, None), 'to_dictionary', None):
                data[snake_key] = getattr(self, snake_key).to_dictionary()

            # If the value doesn't have an to_dictionary() method, i.e., it's not
            # something that subclasses TrafiklabModel, then we can use direct
            # assigment.
            elif getattr(self, snake_key, None):
                data[snake_key] = getattr(self, snake_key, None)
        return data

    # it is a Constructor method
    # noinspection PyPep8Naming
    @classmethod
    def NewFromJson(cls, data, **kwargs):
        if kwargs:
            for key, val in kwargs.items():
                data[utils.to_snake_case(key)] = val

        return cls(**data)
